# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAbstract', '0002_auto_20160126_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedabstract',
            name='paper_title',
            field=models.CharField(default='Default', max_length=60),
            preserve_default=False,
        ),
    ]
