# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAbstract', '0003_submittedabstract_paper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedabstract',
            name='salutation',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
