# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('template', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.InfoPage'),
        ),
    ]
