# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20160204_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='order',
        ),
    ]
