# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20160204_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='infopage',
            name='template',
        ),
        migrations.AlterField(
            model_name='infopage',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
