# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20160208_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
