# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20160208_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
