# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fee_normal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fee_student',
            field=models.BooleanField(default=False),
        ),
    ]
