# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160128_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salutation',
            field=models.CharField(default='Mr.', max_length=6),
            preserve_default=False,
        ),
    ]
